MARKERS = {
    "NSC": [
        "Sox2",
        "Prom1",
        "Slc1a3",
        "Gfap",
        "Fabp7",
        "Jam3",
        "Sox9",
        "Thrsp",
        "Apoe",
        "Clu",
        "Id3",
        "Aldoc",
    ],
    "TAP": ["Egfr", "Mki67", "Ccnd2", "Dlx1", "Dlx2", "Ascl1", "Top2a"],
    "Neuroblast": [
        "Dcx",
        "Dlx1",
        "Ccnd2",
        "Dlx2",
        "Cd24a",
        "Tubb3",
        "Sp9",
        "Fxyd6",
        "Dlx5",
        "Pfn2",
        "Foxc1",
    ],
    "OPC": [
        "Pdgfra",
        "Vcan",
        "Sox10",
        "Cacng4",
        "Olig1",
        "Olig2",
        "Pcdh15",
        "Ppfibp1",
        "Tnr",
        "Cspg4",
        "C1ql1",
        "Epn2",
    ],
    "COP": ["Gpr17", "Sox10", "Olig2", "Itpr2", "Bmp4", "Bcas1", "Tcf7l2"],
    "OL": [
        "Mbp",
        "Mog",
        "Olig2",
        "Plp1",
        "Olig1",
        "Mag",
        "Pdgfra",
        "Opalin",
        "Sox10",
        "Cldn11",
        "Ermn",
    ],
    "Astrocyte": [
        "Aqp4",
        "Gfap",
        "Gja1",
        "Aldh1l1",
        "Slc1a3",
        "Slc1a2",
        "Glul",
        "Aldoc",
        "Agt",
        "Sox9",
        "Vim",
        "S100b",
    ],
    "Microglia": [
        "Tmem119",
        "P2ry12",
        "Cx3cr1",
        "Iba1",
        "Itgam",
        "Fcrls",
        "C1qa",
        "Csf1r",
        "Aif1",
        "C1qc",
        "Hexb",
        "C1qb",
    ],
    "Ependymal": [
        "Tmem212",
        "Ccdc153",
        "Foxj1",
        "Dnah11",
        "Ttll8",
        "Cfap44",
        "Dnai3",
        "Enkur",
        "3300002A11Rik",
        "Ccdc170",
        "Cfap46",
        "Armc3",
    ],
    "Endothelial": [
        "Cldn5",
        "Flt1",
        "Pecam1",
        "Kdr",
        "Fn1",
        "Slc2a1",
        "Ly6c1",
        "Eng",
        "Tek",
        "Ptprb",
        "Igfbp7",
        "Slco1a4",
    ],
    "Mural": [
        "Rgs5",
        "Vtn",
        "Abcc9",
        "Pdgfrb",
        "Kcnj8",
        "Tagln",
        "Vcan",
        "Cald1",
        "Acta2",
        "Notch3",
        "Phldb2",
        "Higd1b",
    ],
}

OL_LINEAGE = {"OPC", "COP", "OL"}
